### PR TITLE
bump version to 5.0.0-SNAPSHOT, upgrade pac4j to 4.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by brunojcm**
adjust all classes to the changes made in the pac4j 4.0

I had to work on that before I could set up everything to work on https://github.com/pac4j/pac4j/issues/1258, so hopefully, it's going to be useful.

### CODE REVIEW

**Comment by leleuj** [comment]
Thanks for the PR. The release date of pac4j v4 is not planned yet, there are still several issues I'd like to address. I'm not in a hurry for this new major version as the stream 3.x is fairly mature.

**Comment by brunojcm** [comment]
All right, I'll be using a version with these changes here, but you can proceed as you think it's best for the project, no worries.

**Comment by leleuj** [comment]
You can update this PR to follow the pac4j v4 evolution, but be aware that this can last a few months...

**Comment by brunojcm** [comment]
Sure! I rely on the fix that is made only on pac4j 4, so I'll have to do it anyway...

**Pull request merged**
