### PR TITLE
Full test coverage for buji-pac4j project

### PR DESCRIPTION
**Pull request by furknyavuz**
Hi @leleuj,

I'm happy to say that I fully covered test cases for buji-pac4j project.

This pull request is raise the overall coverage of the project to 85%.
I also added CODE_COVERAGE.md file to give informations about generating code coverage.

Please let me know if you have any questions.

Furkan Yavuz
DevFactory - Code Quality Team

### CODE REVIEW

**Comment by leleuj** [comment]
Thanks for the pull request. You don't seem to be sync with master, I read: "This branch has conflicts that must be resolved". Can you merge with master?

**Comment by furknyavuz** [comment]
Hi @leleuj,

Yes, I saw the problem too but I didn't understand why this is happening. I'll inverstigate the problem.
That would be great if you tell me the solution if you know.

Thanks,

**Comment by leleuj** [comment]
You need to do: `git pull upstream master` assuming upstream is this repo and that you are on your branch. Generally, you'll find out conflicts which cannot be automatically resolved.

**Comment by furknyavuz** [comment]
Hi @leleuj,

I solved the problem. You can review and merge it if you are feeling ok.

Thanks

**Comment by leleuj** [comment]
Very good! Thanks

**Comment by furknyavuz** [comment]
You'r welcome! :)

**Comment by leleuj** [comment]
It made me curious to run the cobertura plugin on the pac4j project and realized the remaining work....

**Comment by furknyavuz** [comment]
This must be the current coverage for pac4j project. Only scala left uncovered because I don't now scala yet. :)
capture

**Comment by leleuj** [comment]
I meant this one: https://github.com/pac4j/pac4j

**Comment by furknyavuz** [comment]
Ow I see. But that project's size a bit big for us. We are looking for smaller ones. If you have java projects with smaller than 2000 lines please share with us. So we can consider to cover them too with pleasure!

Thanks

**Comment by leleuj** [comment]
Sure. I'm the main developer of pac4j and I meant I could do better tests by looking at the cobertura tests coverage like you did for other pac4j projects.

For small projects to improve, you also have: https://github.com/pac4j/spark-pac4j

**Comment by furknyavuz** [comment]
Great! We will consider spark-pac4j too.

**Pull request merged**
